// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using groupby.Models;

#nullable disable

namespace groupby.Console.Migrations
{
    [DbContext(typeof(TopCCContext))]
    [Migration("20251214225935_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("groupby.Models.Computer", b =>
                {
                    b.Property<int>("ComputerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER")
                        .HasColumnName("power");

                    b.Property<int>("VideoCard")
                        .HasColumnType("INTEGER")
                        .HasColumnName("videocard");

                    b.HasKey("ComputerId");

                    b.ToTable("computer", (string)null);
                });

            modelBuilder.Entity("groupby.Models.CyberClub", b =>
                {
                    b.Property<int>("CyberClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("cyberclub_id");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name_cyberclub");

                    b.HasKey("CyberClubId");

                    b.ToTable("cyberclubs", (string)null);
                });

            modelBuilder.Entity("groupby.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<int>("CyberClubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name_employee");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.Property<int>("Salary")
                        .HasColumnType("INTEGER")
                        .HasColumnName("salary");

                    b.HasKey("EmployeeId");

                    b.HasIndex("CyberClubId");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("groupby.Models.GamingPlace", b =>
                {
                    b.Property<int>("GamingPlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CyberClubId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOrdered")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_ordered");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Seat")
                        .HasColumnType("INTEGER");

                    b.HasKey("GamingPlaceId");

                    b.HasIndex("ComputerId");

                    b.HasIndex("CyberClubId");

                    b.ToTable("gaming_places", (string)null);
                });

            modelBuilder.Entity("groupby.Models.Employee", b =>
                {
                    b.HasOne("groupby.Models.CyberClub", "CyberClub")
                        .WithMany("Employees")
                        .HasForeignKey("CyberClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CyberClub");
                });

            modelBuilder.Entity("groupby.Models.GamingPlace", b =>
                {
                    b.HasOne("groupby.Models.Computer", "Computer")
                        .WithMany("GamingPlaces")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("groupby.Models.CyberClub", "CyberClub")
                        .WithMany("Places")
                        .HasForeignKey("CyberClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");

                    b.Navigation("CyberClub");
                });

            modelBuilder.Entity("groupby.Models.Computer", b =>
                {
                    b.Navigation("GamingPlaces");
                });

            modelBuilder.Entity("groupby.Models.CyberClub", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Places");
                });
#pragma warning restore 612, 618
        }
    }
}
